//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iMidudu.Lucky.Web.BizWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WXUser", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WXUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpenIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PicField;
        
        private bool SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WXCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WXProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WXCountryField;
        
        private System.DateTime RegisterDateField;
        
        private System.DateTime LastActiveTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OpenId {
            get {
                return this.OpenIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OpenIdField, value) != true)) {
                    this.OpenIdField = value;
                    this.RaisePropertyChanged("OpenId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NickName {
            get {
                return this.NickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NickNameField, value) != true)) {
                    this.NickNameField = value;
                    this.RaisePropertyChanged("NickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Pic {
            get {
                return this.PicField;
            }
            set {
                if ((object.ReferenceEquals(this.PicField, value) != true)) {
                    this.PicField = value;
                    this.RaisePropertyChanged("Pic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string WXCity {
            get {
                return this.WXCityField;
            }
            set {
                if ((object.ReferenceEquals(this.WXCityField, value) != true)) {
                    this.WXCityField = value;
                    this.RaisePropertyChanged("WXCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string WXProvince {
            get {
                return this.WXProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.WXProvinceField, value) != true)) {
                    this.WXProvinceField = value;
                    this.RaisePropertyChanged("WXProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string WXCountry {
            get {
                return this.WXCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.WXCountryField, value) != true)) {
                    this.WXCountryField = value;
                    this.RaisePropertyChanged("WXCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime RegisterDate {
            get {
                return this.RegisterDateField;
            }
            set {
                if ((this.RegisterDateField.Equals(value) != true)) {
                    this.RegisterDateField = value;
                    this.RaisePropertyChanged("RegisterDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime LastActiveTime {
            get {
                return this.LastActiveTimeField;
            }
            set {
                if ((this.LastActiveTimeField.Equals(value) != true)) {
                    this.LastActiveTimeField = value;
                    this.RaisePropertyChanged("LastActiveTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScanHistory", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ScanHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid ScanHistoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpenIdField;
        
        private System.Nullable<System.Guid> PrizeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LineTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OsField;
        
        private System.DateTime ScanDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid ScanHistoryId {
            get {
                return this.ScanHistoryIdField;
            }
            set {
                if ((this.ScanHistoryIdField.Equals(value) != true)) {
                    this.ScanHistoryIdField = value;
                    this.RaisePropertyChanged("ScanHistoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OpenId {
            get {
                return this.OpenIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OpenIdField, value) != true)) {
                    this.OpenIdField = value;
                    this.RaisePropertyChanged("OpenId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.Guid> PrizeId {
            get {
                return this.PrizeIdField;
            }
            set {
                if ((this.PrizeIdField.Equals(value) != true)) {
                    this.PrizeIdField = value;
                    this.RaisePropertyChanged("PrizeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string District {
            get {
                return this.DistrictField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictField, value) != true)) {
                    this.DistrictField = value;
                    this.RaisePropertyChanged("District");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string LineType {
            get {
                return this.LineTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.LineTypeField, value) != true)) {
                    this.LineTypeField = value;
                    this.RaisePropertyChanged("LineType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Agent {
            get {
                return this.AgentField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentField, value) != true)) {
                    this.AgentField = value;
                    this.RaisePropertyChanged("Agent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Os {
            get {
                return this.OsField;
            }
            set {
                if ((object.ReferenceEquals(this.OsField, value) != true)) {
                    this.OsField = value;
                    this.RaisePropertyChanged("Os");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.DateTime ScanDate {
            get {
                return this.ScanDateField;
            }
            set {
                if ((this.ScanDateField.Equals(value) != true)) {
                    this.ScanDateField = value;
                    this.RaisePropertyChanged("ScanDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string TicketUrl {
            get {
                return this.TicketUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketUrlField, value) != true)) {
                    this.TicketUrlField = value;
                    this.RaisePropertyChanged("TicketUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string TicketNumber {
            get {
                return this.TicketNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketNumberField, value) != true)) {
                    this.TicketNumberField = value;
                    this.RaisePropertyChanged("TicketNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Acception", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Acception : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid ScanHistoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValidCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid ScanHistoryId {
            get {
                return this.ScanHistoryIdField;
            }
            set {
                if ((this.ScanHistoryIdField.Equals(value) != true)) {
                    this.ScanHistoryIdField = value;
                    this.RaisePropertyChanged("ScanHistoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ValidCode {
            get {
                return this.ValidCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidCodeField, value) != true)) {
                    this.ValidCodeField = value;
                    this.RaisePropertyChanged("ValidCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Prize", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Prize : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid PrizeIdField;
        
        private System.Guid QRCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrizeNameField;
        
        private int QuantityField;
        
        private bool NeedValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        private int DayLimitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid PrizeId {
            get {
                return this.PrizeIdField;
            }
            set {
                if ((this.PrizeIdField.Equals(value) != true)) {
                    this.PrizeIdField = value;
                    this.RaisePropertyChanged("PrizeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid QRCode {
            get {
                return this.QRCodeField;
            }
            set {
                if ((this.QRCodeField.Equals(value) != true)) {
                    this.QRCodeField = value;
                    this.RaisePropertyChanged("QRCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PrizeName {
            get {
                return this.PrizeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PrizeNameField, value) != true)) {
                    this.PrizeNameField = value;
                    this.RaisePropertyChanged("PrizeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool NeedValid {
            get {
                return this.NeedValidField;
            }
            set {
                if ((this.NeedValidField.Equals(value) != true)) {
                    this.NeedValidField = value;
                    this.RaisePropertyChanged("NeedValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int DayLimit {
            get {
                return this.DayLimitField;
            }
            set {
                if ((this.DayLimitField.Equals(value) != true)) {
                    this.DayLimitField = value;
                    this.RaisePropertyChanged("DayLimit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BizWebService.BizWebServiceSoap")]
    public interface BizWebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 ActivityByCodeResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActivityByCode", ReplyAction="*")]
        iMidudu.Lucky.Web.BizWebService.ActivityByCodeResponse ActivityByCode(iMidudu.Lucky.Web.BizWebService.ActivityByCodeRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 user 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveWXUser", ReplyAction="*")]
        iMidudu.Lucky.Web.BizWebService.SaveWXUserResponse SaveWXUser(iMidudu.Lucky.Web.BizWebService.SaveWXUserRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 History 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertScanHistory", ReplyAction="*")]
        iMidudu.Lucky.Web.BizWebService.InsertScanHistoryResponse InsertScanHistory(iMidudu.Lucky.Web.BizWebService.InsertScanHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateScanHistory", ReplyAction="*")]
        void UpdateScanHistory(System.Guid ScanHistoryId, System.Guid PrizeId);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 accept 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveAcception", ReplyAction="*")]
        iMidudu.Lucky.Web.BizWebService.SaveAcceptionResponse SaveAcception(iMidudu.Lucky.Web.BizWebService.SaveAcceptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePrize", ReplyAction="*")]
        void UpdatePrize(System.Guid PrizeId, int Quantity);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 PrizeLotteryResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrizeLottery", ReplyAction="*")]
        iMidudu.Lucky.Web.BizWebService.PrizeLotteryResponse PrizeLottery(iMidudu.Lucky.Web.BizWebService.PrizeLotteryRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 SelectWXUserByScanHistoryIdResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectWXUserByScanHistoryId", ReplyAction="*")]
        iMidudu.Lucky.Web.BizWebService.SelectWXUserByScanHistoryIdResponse SelectWXUserByScanHistoryId(iMidudu.Lucky.Web.BizWebService.SelectWXUserByScanHistoryIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivityByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivityByCode", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.BizWebService.ActivityByCodeRequestBody Body;
        
        public ActivityByCodeRequest() {
        }
        
        public ActivityByCodeRequest(iMidudu.Lucky.Web.BizWebService.ActivityByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActivityByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid Code;
        
        public ActivityByCodeRequestBody() {
        }
        
        public ActivityByCodeRequestBody(System.Guid Code) {
            this.Code = Code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivityByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivityByCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.BizWebService.ActivityByCodeResponseBody Body;
        
        public ActivityByCodeResponse() {
        }
        
        public ActivityByCodeResponse(iMidudu.Lucky.Web.BizWebService.ActivityByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActivityByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ActivityByCodeResult;
        
        public ActivityByCodeResponseBody() {
        }
        
        public ActivityByCodeResponseBody(string ActivityByCodeResult) {
            this.ActivityByCodeResult = ActivityByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveWXUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveWXUser", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.BizWebService.SaveWXUserRequestBody Body;
        
        public SaveWXUserRequest() {
        }
        
        public SaveWXUserRequest(iMidudu.Lucky.Web.BizWebService.SaveWXUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveWXUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public iMidudu.Lucky.Web.BizWebService.WXUser user;
        
        public SaveWXUserRequestBody() {
        }
        
        public SaveWXUserRequestBody(iMidudu.Lucky.Web.BizWebService.WXUser user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveWXUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveWXUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.BizWebService.SaveWXUserResponseBody Body;
        
        public SaveWXUserResponse() {
        }
        
        public SaveWXUserResponse(iMidudu.Lucky.Web.BizWebService.SaveWXUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveWXUserResponseBody {
        
        public SaveWXUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertScanHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertScanHistory", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.BizWebService.InsertScanHistoryRequestBody Body;
        
        public InsertScanHistoryRequest() {
        }
        
        public InsertScanHistoryRequest(iMidudu.Lucky.Web.BizWebService.InsertScanHistoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertScanHistoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public iMidudu.Lucky.Web.BizWebService.ScanHistory History;
        
        public InsertScanHistoryRequestBody() {
        }
        
        public InsertScanHistoryRequestBody(iMidudu.Lucky.Web.BizWebService.ScanHistory History) {
            this.History = History;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertScanHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertScanHistoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.BizWebService.InsertScanHistoryResponseBody Body;
        
        public InsertScanHistoryResponse() {
        }
        
        public InsertScanHistoryResponse(iMidudu.Lucky.Web.BizWebService.InsertScanHistoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertScanHistoryResponseBody {
        
        public InsertScanHistoryResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveAcceptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveAcception", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.BizWebService.SaveAcceptionRequestBody Body;
        
        public SaveAcceptionRequest() {
        }
        
        public SaveAcceptionRequest(iMidudu.Lucky.Web.BizWebService.SaveAcceptionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveAcceptionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public iMidudu.Lucky.Web.BizWebService.Acception accept;
        
        public SaveAcceptionRequestBody() {
        }
        
        public SaveAcceptionRequestBody(iMidudu.Lucky.Web.BizWebService.Acception accept) {
            this.accept = accept;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveAcceptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveAcceptionResponse", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.BizWebService.SaveAcceptionResponseBody Body;
        
        public SaveAcceptionResponse() {
        }
        
        public SaveAcceptionResponse(iMidudu.Lucky.Web.BizWebService.SaveAcceptionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveAcceptionResponseBody {
        
        public SaveAcceptionResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrizeLotteryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrizeLottery", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.BizWebService.PrizeLotteryRequestBody Body;
        
        public PrizeLotteryRequest() {
        }
        
        public PrizeLotteryRequest(iMidudu.Lucky.Web.BizWebService.PrizeLotteryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrizeLotteryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid QRCode;
        
        public PrizeLotteryRequestBody() {
        }
        
        public PrizeLotteryRequestBody(System.Guid QRCode) {
            this.QRCode = QRCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrizeLotteryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrizeLotteryResponse", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.BizWebService.PrizeLotteryResponseBody Body;
        
        public PrizeLotteryResponse() {
        }
        
        public PrizeLotteryResponse(iMidudu.Lucky.Web.BizWebService.PrizeLotteryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrizeLotteryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public iMidudu.Lucky.Web.BizWebService.Prize PrizeLotteryResult;
        
        public PrizeLotteryResponseBody() {
        }
        
        public PrizeLotteryResponseBody(iMidudu.Lucky.Web.BizWebService.Prize PrizeLotteryResult) {
            this.PrizeLotteryResult = PrizeLotteryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectWXUserByScanHistoryIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectWXUserByScanHistoryId", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.BizWebService.SelectWXUserByScanHistoryIdRequestBody Body;
        
        public SelectWXUserByScanHistoryIdRequest() {
        }
        
        public SelectWXUserByScanHistoryIdRequest(iMidudu.Lucky.Web.BizWebService.SelectWXUserByScanHistoryIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectWXUserByScanHistoryIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid ScanHistoryId;
        
        public SelectWXUserByScanHistoryIdRequestBody() {
        }
        
        public SelectWXUserByScanHistoryIdRequestBody(System.Guid ScanHistoryId) {
            this.ScanHistoryId = ScanHistoryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectWXUserByScanHistoryIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectWXUserByScanHistoryIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.BizWebService.SelectWXUserByScanHistoryIdResponseBody Body;
        
        public SelectWXUserByScanHistoryIdResponse() {
        }
        
        public SelectWXUserByScanHistoryIdResponse(iMidudu.Lucky.Web.BizWebService.SelectWXUserByScanHistoryIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectWXUserByScanHistoryIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public iMidudu.Lucky.Web.BizWebService.WXUser SelectWXUserByScanHistoryIdResult;
        
        public SelectWXUserByScanHistoryIdResponseBody() {
        }
        
        public SelectWXUserByScanHistoryIdResponseBody(iMidudu.Lucky.Web.BizWebService.WXUser SelectWXUserByScanHistoryIdResult) {
            this.SelectWXUserByScanHistoryIdResult = SelectWXUserByScanHistoryIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BizWebServiceSoapChannel : iMidudu.Lucky.Web.BizWebService.BizWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BizWebServiceSoapClient : System.ServiceModel.ClientBase<iMidudu.Lucky.Web.BizWebService.BizWebServiceSoap>, iMidudu.Lucky.Web.BizWebService.BizWebServiceSoap {
        
        public BizWebServiceSoapClient() {
        }
        
        public BizWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BizWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iMidudu.Lucky.Web.BizWebService.ActivityByCodeResponse iMidudu.Lucky.Web.BizWebService.BizWebServiceSoap.ActivityByCode(iMidudu.Lucky.Web.BizWebService.ActivityByCodeRequest request) {
            return base.Channel.ActivityByCode(request);
        }
        
        public string ActivityByCode(System.Guid Code) {
            iMidudu.Lucky.Web.BizWebService.ActivityByCodeRequest inValue = new iMidudu.Lucky.Web.BizWebService.ActivityByCodeRequest();
            inValue.Body = new iMidudu.Lucky.Web.BizWebService.ActivityByCodeRequestBody();
            inValue.Body.Code = Code;
            iMidudu.Lucky.Web.BizWebService.ActivityByCodeResponse retVal = ((iMidudu.Lucky.Web.BizWebService.BizWebServiceSoap)(this)).ActivityByCode(inValue);
            return retVal.Body.ActivityByCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iMidudu.Lucky.Web.BizWebService.SaveWXUserResponse iMidudu.Lucky.Web.BizWebService.BizWebServiceSoap.SaveWXUser(iMidudu.Lucky.Web.BizWebService.SaveWXUserRequest request) {
            return base.Channel.SaveWXUser(request);
        }
        
        public void SaveWXUser(iMidudu.Lucky.Web.BizWebService.WXUser user) {
            iMidudu.Lucky.Web.BizWebService.SaveWXUserRequest inValue = new iMidudu.Lucky.Web.BizWebService.SaveWXUserRequest();
            inValue.Body = new iMidudu.Lucky.Web.BizWebService.SaveWXUserRequestBody();
            inValue.Body.user = user;
            iMidudu.Lucky.Web.BizWebService.SaveWXUserResponse retVal = ((iMidudu.Lucky.Web.BizWebService.BizWebServiceSoap)(this)).SaveWXUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iMidudu.Lucky.Web.BizWebService.InsertScanHistoryResponse iMidudu.Lucky.Web.BizWebService.BizWebServiceSoap.InsertScanHistory(iMidudu.Lucky.Web.BizWebService.InsertScanHistoryRequest request) {
            return base.Channel.InsertScanHistory(request);
        }
        
        public void InsertScanHistory(iMidudu.Lucky.Web.BizWebService.ScanHistory History) {
            iMidudu.Lucky.Web.BizWebService.InsertScanHistoryRequest inValue = new iMidudu.Lucky.Web.BizWebService.InsertScanHistoryRequest();
            inValue.Body = new iMidudu.Lucky.Web.BizWebService.InsertScanHistoryRequestBody();
            inValue.Body.History = History;
            iMidudu.Lucky.Web.BizWebService.InsertScanHistoryResponse retVal = ((iMidudu.Lucky.Web.BizWebService.BizWebServiceSoap)(this)).InsertScanHistory(inValue);
        }
        
        public void UpdateScanHistory(System.Guid ScanHistoryId, System.Guid PrizeId) {
            base.Channel.UpdateScanHistory(ScanHistoryId, PrizeId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iMidudu.Lucky.Web.BizWebService.SaveAcceptionResponse iMidudu.Lucky.Web.BizWebService.BizWebServiceSoap.SaveAcception(iMidudu.Lucky.Web.BizWebService.SaveAcceptionRequest request) {
            return base.Channel.SaveAcception(request);
        }
        
        public void SaveAcception(iMidudu.Lucky.Web.BizWebService.Acception accept) {
            iMidudu.Lucky.Web.BizWebService.SaveAcceptionRequest inValue = new iMidudu.Lucky.Web.BizWebService.SaveAcceptionRequest();
            inValue.Body = new iMidudu.Lucky.Web.BizWebService.SaveAcceptionRequestBody();
            inValue.Body.accept = accept;
            iMidudu.Lucky.Web.BizWebService.SaveAcceptionResponse retVal = ((iMidudu.Lucky.Web.BizWebService.BizWebServiceSoap)(this)).SaveAcception(inValue);
        }
        
        public void UpdatePrize(System.Guid PrizeId, int Quantity) {
            base.Channel.UpdatePrize(PrizeId, Quantity);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iMidudu.Lucky.Web.BizWebService.PrizeLotteryResponse iMidudu.Lucky.Web.BizWebService.BizWebServiceSoap.PrizeLottery(iMidudu.Lucky.Web.BizWebService.PrizeLotteryRequest request) {
            return base.Channel.PrizeLottery(request);
        }
        
        public iMidudu.Lucky.Web.BizWebService.Prize PrizeLottery(System.Guid QRCode) {
            iMidudu.Lucky.Web.BizWebService.PrizeLotteryRequest inValue = new iMidudu.Lucky.Web.BizWebService.PrizeLotteryRequest();
            inValue.Body = new iMidudu.Lucky.Web.BizWebService.PrizeLotteryRequestBody();
            inValue.Body.QRCode = QRCode;
            iMidudu.Lucky.Web.BizWebService.PrizeLotteryResponse retVal = ((iMidudu.Lucky.Web.BizWebService.BizWebServiceSoap)(this)).PrizeLottery(inValue);
            return retVal.Body.PrizeLotteryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iMidudu.Lucky.Web.BizWebService.SelectWXUserByScanHistoryIdResponse iMidudu.Lucky.Web.BizWebService.BizWebServiceSoap.SelectWXUserByScanHistoryId(iMidudu.Lucky.Web.BizWebService.SelectWXUserByScanHistoryIdRequest request) {
            return base.Channel.SelectWXUserByScanHistoryId(request);
        }
        
        public iMidudu.Lucky.Web.BizWebService.WXUser SelectWXUserByScanHistoryId(System.Guid ScanHistoryId) {
            iMidudu.Lucky.Web.BizWebService.SelectWXUserByScanHistoryIdRequest inValue = new iMidudu.Lucky.Web.BizWebService.SelectWXUserByScanHistoryIdRequest();
            inValue.Body = new iMidudu.Lucky.Web.BizWebService.SelectWXUserByScanHistoryIdRequestBody();
            inValue.Body.ScanHistoryId = ScanHistoryId;
            iMidudu.Lucky.Web.BizWebService.SelectWXUserByScanHistoryIdResponse retVal = ((iMidudu.Lucky.Web.BizWebService.BizWebServiceSoap)(this)).SelectWXUserByScanHistoryId(inValue);
            return retVal.Body.SelectWXUserByScanHistoryIdResult;
        }
    }
}
