//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iMidudu.Lucky.Web.BizWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BizWebService.BizWebServiceSoap")]
    public interface BizWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name ActivityByCodeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActivityByCode", ReplyAction="*")]
        iMidudu.Lucky.Web.BizWebService.ActivityByCodeResponse ActivityByCode(iMidudu.Lucky.Web.BizWebService.ActivityByCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivityByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivityByCode", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.BizWebService.ActivityByCodeRequestBody Body;
        
        public ActivityByCodeRequest() {
        }
        
        public ActivityByCodeRequest(iMidudu.Lucky.Web.BizWebService.ActivityByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActivityByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid Code;
        
        public ActivityByCodeRequestBody() {
        }
        
        public ActivityByCodeRequestBody(System.Guid Code) {
            this.Code = Code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivityByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivityByCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.BizWebService.ActivityByCodeResponseBody Body;
        
        public ActivityByCodeResponse() {
        }
        
        public ActivityByCodeResponse(iMidudu.Lucky.Web.BizWebService.ActivityByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActivityByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ActivityByCodeResult;
        
        public ActivityByCodeResponseBody() {
        }
        
        public ActivityByCodeResponseBody(string ActivityByCodeResult) {
            this.ActivityByCodeResult = ActivityByCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BizWebServiceSoapChannel : iMidudu.Lucky.Web.BizWebService.BizWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BizWebServiceSoapClient : System.ServiceModel.ClientBase<iMidudu.Lucky.Web.BizWebService.BizWebServiceSoap>, iMidudu.Lucky.Web.BizWebService.BizWebServiceSoap {
        
        public BizWebServiceSoapClient() {
        }
        
        public BizWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BizWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iMidudu.Lucky.Web.BizWebService.ActivityByCodeResponse iMidudu.Lucky.Web.BizWebService.BizWebServiceSoap.ActivityByCode(iMidudu.Lucky.Web.BizWebService.ActivityByCodeRequest request) {
            return base.Channel.ActivityByCode(request);
        }
        
        public string ActivityByCode(System.Guid Code) {
            iMidudu.Lucky.Web.BizWebService.ActivityByCodeRequest inValue = new iMidudu.Lucky.Web.BizWebService.ActivityByCodeRequest();
            inValue.Body = new iMidudu.Lucky.Web.BizWebService.ActivityByCodeRequestBody();
            inValue.Body.Code = Code;
            iMidudu.Lucky.Web.BizWebService.ActivityByCodeResponse retVal = ((iMidudu.Lucky.Web.BizWebService.BizWebServiceSoap)(this)).ActivityByCode(inValue);
            return retVal.Body.ActivityByCodeResult;
        }
    }
}
