//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iMidudu.Lucky.Web.WeChatWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpenIdResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OpenIdResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string access_tokenField;
        
        private int expires_inField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string refresh_tokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string openidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string scopeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string access_token {
            get {
                return this.access_tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.access_tokenField, value) != true)) {
                    this.access_tokenField = value;
                    this.RaisePropertyChanged("access_token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int expires_in {
            get {
                return this.expires_inField;
            }
            set {
                if ((this.expires_inField.Equals(value) != true)) {
                    this.expires_inField = value;
                    this.RaisePropertyChanged("expires_in");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string refresh_token {
            get {
                return this.refresh_tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.refresh_tokenField, value) != true)) {
                    this.refresh_tokenField = value;
                    this.RaisePropertyChanged("refresh_token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string openid {
            get {
                return this.openidField;
            }
            set {
                if ((object.ReferenceEquals(this.openidField, value) != true)) {
                    this.openidField = value;
                    this.RaisePropertyChanged("openid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string scope {
            get {
                return this.scopeField;
            }
            set {
                if ((object.ReferenceEquals(this.scopeField, value) != true)) {
                    this.scopeField = value;
                    this.RaisePropertyChanged("scope");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string openidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nicknameField;
        
        private int sexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string languageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string provinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string headimgurlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unionidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private iMidudu.Lucky.Web.WeChatWebService.ArrayOfString privilegeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string openid {
            get {
                return this.openidField;
            }
            set {
                if ((object.ReferenceEquals(this.openidField, value) != true)) {
                    this.openidField = value;
                    this.RaisePropertyChanged("openid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nickname {
            get {
                return this.nicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.nicknameField, value) != true)) {
                    this.nicknameField = value;
                    this.RaisePropertyChanged("nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int sex {
            get {
                return this.sexField;
            }
            set {
                if ((this.sexField.Equals(value) != true)) {
                    this.sexField = value;
                    this.RaisePropertyChanged("sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                if ((object.ReferenceEquals(this.languageField, value) != true)) {
                    this.languageField = value;
                    this.RaisePropertyChanged("language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string province {
            get {
                return this.provinceField;
            }
            set {
                if ((object.ReferenceEquals(this.provinceField, value) != true)) {
                    this.provinceField = value;
                    this.RaisePropertyChanged("province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                if ((object.ReferenceEquals(this.countryField, value) != true)) {
                    this.countryField = value;
                    this.RaisePropertyChanged("country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string headimgurl {
            get {
                return this.headimgurlField;
            }
            set {
                if ((object.ReferenceEquals(this.headimgurlField, value) != true)) {
                    this.headimgurlField = value;
                    this.RaisePropertyChanged("headimgurl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string unionid {
            get {
                return this.unionidField;
            }
            set {
                if ((object.ReferenceEquals(this.unionidField, value) != true)) {
                    this.unionidField = value;
                    this.RaisePropertyChanged("unionid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public iMidudu.Lucky.Web.WeChatWebService.ArrayOfString privilege {
            get {
                return this.privilegeField;
            }
            set {
                if ((object.ReferenceEquals(this.privilegeField, value) != true)) {
                    this.privilegeField = value;
                    this.RaisePropertyChanged("privilege");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WXconfig", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WXconfig : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string appIdField;
        
        private long timestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nonceStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string signatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private iMidudu.Lucky.Web.WeChatWebService.ArrayOfString jsApiListField;
        
        private bool debugField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ticketField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string appId {
            get {
                return this.appIdField;
            }
            set {
                if ((object.ReferenceEquals(this.appIdField, value) != true)) {
                    this.appIdField = value;
                    this.RaisePropertyChanged("appId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long timestamp {
            get {
                return this.timestampField;
            }
            set {
                if ((this.timestampField.Equals(value) != true)) {
                    this.timestampField = value;
                    this.RaisePropertyChanged("timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nonceStr {
            get {
                return this.nonceStrField;
            }
            set {
                if ((object.ReferenceEquals(this.nonceStrField, value) != true)) {
                    this.nonceStrField = value;
                    this.RaisePropertyChanged("nonceStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                if ((object.ReferenceEquals(this.signatureField, value) != true)) {
                    this.signatureField = value;
                    this.RaisePropertyChanged("signature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public iMidudu.Lucky.Web.WeChatWebService.ArrayOfString jsApiList {
            get {
                return this.jsApiListField;
            }
            set {
                if ((object.ReferenceEquals(this.jsApiListField, value) != true)) {
                    this.jsApiListField = value;
                    this.RaisePropertyChanged("jsApiList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool debug {
            get {
                return this.debugField;
            }
            set {
                if ((this.debugField.Equals(value) != true)) {
                    this.debugField = value;
                    this.RaisePropertyChanged("debug");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ticket {
            get {
                return this.ticketField;
            }
            set {
                if ((object.ReferenceEquals(this.ticketField, value) != true)) {
                    this.ticketField = value;
                    this.RaisePropertyChanged("ticket");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeChatWebService.WeChatWebServiceSoap")]
    public interface WeChatWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name code from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getOpenId", ReplyAction="*")]
        iMidudu.Lucky.Web.WeChatWebService.getOpenIdResponse getOpenId(iMidudu.Lucky.Web.WeChatWebService.getOpenIdRequest request);
        
        // CODEGEN: Generating message contract since element name openid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserInfo", ReplyAction="*")]
        iMidudu.Lucky.Web.WeChatWebService.getUserInfoResponse getUserInfo(iMidudu.Lucky.Web.WeChatWebService.getUserInfoRequest request);
        
        // CODEGEN: Generating message contract since element name Url from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Config", ReplyAction="*")]
        iMidudu.Lucky.Web.WeChatWebService.ConfigResponse Config(iMidudu.Lucky.Web.WeChatWebService.ConfigRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOpenIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOpenId", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.WeChatWebService.getOpenIdRequestBody Body;
        
        public getOpenIdRequest() {
        }
        
        public getOpenIdRequest(iMidudu.Lucky.Web.WeChatWebService.getOpenIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getOpenIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string code;
        
        public getOpenIdRequestBody() {
        }
        
        public getOpenIdRequestBody(string code) {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOpenIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOpenIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.WeChatWebService.getOpenIdResponseBody Body;
        
        public getOpenIdResponse() {
        }
        
        public getOpenIdResponse(iMidudu.Lucky.Web.WeChatWebService.getOpenIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getOpenIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public iMidudu.Lucky.Web.WeChatWebService.OpenIdResponse getOpenIdResult;
        
        public getOpenIdResponseBody() {
        }
        
        public getOpenIdResponseBody(iMidudu.Lucky.Web.WeChatWebService.OpenIdResponse getOpenIdResult) {
            this.getOpenIdResult = getOpenIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserInfo", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.WeChatWebService.getUserInfoRequestBody Body;
        
        public getUserInfoRequest() {
        }
        
        public getUserInfoRequest(iMidudu.Lucky.Web.WeChatWebService.getUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public iMidudu.Lucky.Web.WeChatWebService.OpenIdResponse openid;
        
        public getUserInfoRequestBody() {
        }
        
        public getUserInfoRequestBody(iMidudu.Lucky.Web.WeChatWebService.OpenIdResponse openid) {
            this.openid = openid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.WeChatWebService.getUserInfoResponseBody Body;
        
        public getUserInfoResponse() {
        }
        
        public getUserInfoResponse(iMidudu.Lucky.Web.WeChatWebService.getUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public iMidudu.Lucky.Web.WeChatWebService.UserInfo getUserInfoResult;
        
        public getUserInfoResponseBody() {
        }
        
        public getUserInfoResponseBody(iMidudu.Lucky.Web.WeChatWebService.UserInfo getUserInfoResult) {
            this.getUserInfoResult = getUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfigRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Config", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.WeChatWebService.ConfigRequestBody Body;
        
        public ConfigRequest() {
        }
        
        public ConfigRequest(iMidudu.Lucky.Web.WeChatWebService.ConfigRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfigRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Url;
        
        public ConfigRequestBody() {
        }
        
        public ConfigRequestBody(string Url) {
            this.Url = Url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfigResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfigResponse", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.WeChatWebService.ConfigResponseBody Body;
        
        public ConfigResponse() {
        }
        
        public ConfigResponse(iMidudu.Lucky.Web.WeChatWebService.ConfigResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfigResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public iMidudu.Lucky.Web.WeChatWebService.WXconfig ConfigResult;
        
        public ConfigResponseBody() {
        }
        
        public ConfigResponseBody(iMidudu.Lucky.Web.WeChatWebService.WXconfig ConfigResult) {
            this.ConfigResult = ConfigResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WeChatWebServiceSoapChannel : iMidudu.Lucky.Web.WeChatWebService.WeChatWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeChatWebServiceSoapClient : System.ServiceModel.ClientBase<iMidudu.Lucky.Web.WeChatWebService.WeChatWebServiceSoap>, iMidudu.Lucky.Web.WeChatWebService.WeChatWebServiceSoap {
        
        public WeChatWebServiceSoapClient() {
        }
        
        public WeChatWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeChatWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeChatWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeChatWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iMidudu.Lucky.Web.WeChatWebService.getOpenIdResponse iMidudu.Lucky.Web.WeChatWebService.WeChatWebServiceSoap.getOpenId(iMidudu.Lucky.Web.WeChatWebService.getOpenIdRequest request) {
            return base.Channel.getOpenId(request);
        }
        
        public iMidudu.Lucky.Web.WeChatWebService.OpenIdResponse getOpenId(string code) {
            iMidudu.Lucky.Web.WeChatWebService.getOpenIdRequest inValue = new iMidudu.Lucky.Web.WeChatWebService.getOpenIdRequest();
            inValue.Body = new iMidudu.Lucky.Web.WeChatWebService.getOpenIdRequestBody();
            inValue.Body.code = code;
            iMidudu.Lucky.Web.WeChatWebService.getOpenIdResponse retVal = ((iMidudu.Lucky.Web.WeChatWebService.WeChatWebServiceSoap)(this)).getOpenId(inValue);
            return retVal.Body.getOpenIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iMidudu.Lucky.Web.WeChatWebService.getUserInfoResponse iMidudu.Lucky.Web.WeChatWebService.WeChatWebServiceSoap.getUserInfo(iMidudu.Lucky.Web.WeChatWebService.getUserInfoRequest request) {
            return base.Channel.getUserInfo(request);
        }
        
        public iMidudu.Lucky.Web.WeChatWebService.UserInfo getUserInfo(iMidudu.Lucky.Web.WeChatWebService.OpenIdResponse openid) {
            iMidudu.Lucky.Web.WeChatWebService.getUserInfoRequest inValue = new iMidudu.Lucky.Web.WeChatWebService.getUserInfoRequest();
            inValue.Body = new iMidudu.Lucky.Web.WeChatWebService.getUserInfoRequestBody();
            inValue.Body.openid = openid;
            iMidudu.Lucky.Web.WeChatWebService.getUserInfoResponse retVal = ((iMidudu.Lucky.Web.WeChatWebService.WeChatWebServiceSoap)(this)).getUserInfo(inValue);
            return retVal.Body.getUserInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iMidudu.Lucky.Web.WeChatWebService.ConfigResponse iMidudu.Lucky.Web.WeChatWebService.WeChatWebServiceSoap.Config(iMidudu.Lucky.Web.WeChatWebService.ConfigRequest request) {
            return base.Channel.Config(request);
        }
        
        public iMidudu.Lucky.Web.WeChatWebService.WXconfig Config(string Url) {
            iMidudu.Lucky.Web.WeChatWebService.ConfigRequest inValue = new iMidudu.Lucky.Web.WeChatWebService.ConfigRequest();
            inValue.Body = new iMidudu.Lucky.Web.WeChatWebService.ConfigRequestBody();
            inValue.Body.Url = Url;
            iMidudu.Lucky.Web.WeChatWebService.ConfigResponse retVal = ((iMidudu.Lucky.Web.WeChatWebService.WeChatWebServiceSoap)(this)).Config(inValue);
            return retVal.Body.ConfigResult;
        }
    }
}
