//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iMidudu.Lucky.Web.SMSWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSWebService.SMSWebServiceSoap")]
    public interface SMSWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name apikey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendValidCode", ReplyAction="*")]
        iMidudu.Lucky.Web.SMSWebService.SendValidCodeResponse SendValidCode(iMidudu.Lucky.Web.SMSWebService.SendValidCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendValidCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendValidCode", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.SMSWebService.SendValidCodeRequestBody Body;
        
        public SendValidCodeRequest() {
        }
        
        public SendValidCodeRequest(iMidudu.Lucky.Web.SMSWebService.SendValidCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendValidCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apikey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string format;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string toMobile;
        
        public SendValidCodeRequestBody() {
        }
        
        public SendValidCodeRequestBody(string apikey, string format, string toMobile) {
            this.apikey = apikey;
            this.format = format;
            this.toMobile = toMobile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendValidCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendValidCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public iMidudu.Lucky.Web.SMSWebService.SendValidCodeResponseBody Body;
        
        public SendValidCodeResponse() {
        }
        
        public SendValidCodeResponse(iMidudu.Lucky.Web.SMSWebService.SendValidCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendValidCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendValidCodeResult;
        
        public SendValidCodeResponseBody() {
        }
        
        public SendValidCodeResponseBody(string SendValidCodeResult) {
            this.SendValidCodeResult = SendValidCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSWebServiceSoapChannel : iMidudu.Lucky.Web.SMSWebService.SMSWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSWebServiceSoapClient : System.ServiceModel.ClientBase<iMidudu.Lucky.Web.SMSWebService.SMSWebServiceSoap>, iMidudu.Lucky.Web.SMSWebService.SMSWebServiceSoap {
        
        public SMSWebServiceSoapClient() {
        }
        
        public SMSWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iMidudu.Lucky.Web.SMSWebService.SendValidCodeResponse iMidudu.Lucky.Web.SMSWebService.SMSWebServiceSoap.SendValidCode(iMidudu.Lucky.Web.SMSWebService.SendValidCodeRequest request) {
            return base.Channel.SendValidCode(request);
        }
        
        public string SendValidCode(string apikey, string format, string toMobile) {
            iMidudu.Lucky.Web.SMSWebService.SendValidCodeRequest inValue = new iMidudu.Lucky.Web.SMSWebService.SendValidCodeRequest();
            inValue.Body = new iMidudu.Lucky.Web.SMSWebService.SendValidCodeRequestBody();
            inValue.Body.apikey = apikey;
            inValue.Body.format = format;
            inValue.Body.toMobile = toMobile;
            iMidudu.Lucky.Web.SMSWebService.SendValidCodeResponse retVal = ((iMidudu.Lucky.Web.SMSWebService.SMSWebServiceSoap)(this)).SendValidCode(inValue);
            return retVal.Body.SendValidCodeResult;
        }
    }
}
